{
  finished: {
    Status: RanToCompletion
  },
  running: {
    Status: WaitingForActivation
  },
  withResult: {
    Status: RanToCompletion,
    Result: Value
  },
  withException: {
    Status: Faulted,
    Exception: {
      Type: AggregateException,
      InnerExceptions: [
        {
          Type: Exception,
          Message: the exception
        }
      ],
      Message: One or more errors occurred. (the exception)
    }
  },
  withExceptionAndResult: {
    Status: Faulted,
    Exception: {
      Type: AggregateException,
      InnerExceptions: [
        {
          Type: Exception,
          Message: the exception
        }
      ],
      Message: One or more errors occurred. (the exception)
    }
  },
  canceledAndResult: {
    Status: Canceled
  }
}