{
  Type: Exception,
  Message: The Message,
  StackTrace:
at Tests.TaskMethodThatThrowsGeneric()
at InnerVerifier.<ThrowsTask>d__38`1.MoveNext()
}