{
  Type: Exception,
  Message: The Message,
  StackTrace: 
at Tests.TaskMethodThatThrows()
at VerifyTests.InnerVerifier.ThrowsAsync(Func`1 target)
}