{
  Type: Exception,
  Message: The Message,
  StackTrace:
at Tests.ValueTaskMethodThatThrows()
at InnerVerifier.ThrowsValueTask(Func`1 target)
}