{
  Type: Exception,
  Message: The Message,
  StackTrace:
at Tests.TaskMethodThatThrows()
at InnerVerifier.ThrowsTask(Func`1 target)
}